version: 2
jobs:
  build:
    working_directory: /go/crawler
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run:
          name: Go build
          command: go build -v ./bin/crawler
      - run:
          name: Run tests
          command: go test -race -cover -coverprofile=${CIRCLE_COVERAGE_REPORT}/coverage.out ./...
  dockerfile:
    working_directory: /crawler
    docker:
      - image: docker:18.03
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Build Dockerfile
          command: docker build .
workflows:
  version: 2
  test-and-build-docker:
    jobs:
      - build
      - dockerfile:
          requires:
            - build
